# Generated by Django 4.2.15 on 2024-08-14 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empresa',
            fields=[
                ('EmpresaId', models.AutoField(db_column='EmpresaId', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(db_column='Nombre', max_length=50)),
                ('Fecha', models.DateField(db_column='Fecha')),
                ('Tipo', models.CharField(db_column='Tipo', max_length=1, null=True)),
                ('Comentarios', models.CharField(blank=True, db_column='Comentarios', max_length=1020)),
                ('Favorita', models.BooleanField(blank=True, db_column='Favorita')),
            ],
            options={
                'db_table': 'empresa',
                'managed': False,
            },
        ),
    ]
